"""Add RecurringTransactionRule model

Revision ID: 063088c5bc03
Revises: b759da14f8a9
Create Date: 2025-06-11 12:19:18.834529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063088c5bc03'
down_revision = 'b759da14f8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transaction_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_occurrence_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_transaction_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_transaction_rule_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_transaction_rule_next_occurrence_date'), ['next_occurrence_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_transaction_rule_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transaction_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_transaction_rule_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_transaction_rule_next_occurrence_date'))
        batch_op.drop_index(batch_op.f('ix_recurring_transaction_rule_category_id'))

    op.drop_table('recurring_transaction_rule')
    # ### end Alembic commands ###
